version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.3-stretch-browsers
    environment:
      TEST_URL: http://127.0.0.1
      REACT_APP_USERS_SERVICE_URL: http://127.0.0.1
      DISPLAY: :99.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - run:
          name: install-testcafe
          command: npm install testcafe
      - run:
          name: sleep
          command: sleep 3
      - run:
          name: tests
          command: bash test.sh stage
