version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.3-stretch-browsers
    environment:
      TEST_URL: http://127.0.0.1
      REACT_APP_USERS_SERVICE_URL: http://127.0.0.1
      DISPLAY: :99.0
      DOCKER_HOST: 127.0.0.1
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-testcafe
          command: 'sudo npm install -g testcafe'
      - run:
          name: launch-containers
          command: |
            set -x
            sudo docker-compose -f docker-compose-prod.yml up -d
      - run:
          name: tests
          command: 'bash test.sh stage'
