version: 2 #CircleCI version
jobs:
  build:
    machine:
          image: ubuntu-1604:201903-01
    environment:
      DISPLAY: :99.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "58:32:cf:bf:61:22:eb:cd:c7:0f:30:e0:af:f7:21:ff"
      - checkout
      # - setup_remote_docker
      - run:
          name: set-variables
          command: |
            echo 'export TEST_URL=$(echo $DOCKER_HOST | sed "s#tcp://#http://#" | sed  -r "s/:[0-9]+//")' >> $BASH_ENV
            echo 'export REACT_APP_USERS_SERVICE_URL=$TEST_URL' >> $BASH_ENV
            echo $TEST_URL
            echo $REACT_APP_USERS_SERVICE_URL
      - run:
          name: test-variables
          command: |
            echo $TEST_URL
            echo $REACT_APP_USERS_SERVICE_URL
      - run:
          name: launch-containers-machine
          command: docker-compose -f docker-compose-dev.yml up -d --build
          # name: launch-containers
          # command: |
          #   set -x
          #   echo $DOCKER_HOST
          #   echo $DOCKER_CERT_PATH
          #   docker-compose --tlsverify -H=$DOCKER_HOST --tlscacert=$DOCKER_CERT_PATH/ca.pem --tlscert=$DOCKER_CERT_PATH/cert.pem --tlskey=$DOCKER_CERT_PATH/key.pem -f docker-compose-dev.yml up -d --build
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: install-testcafe
          command: 'sudo npm install -g testcafe'
      - run:
          name: tests
          command: 'bash test.sh stage'
