# base image
FROM node:lts

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

ARG RECAPTCHA_SITE_KEY
ENV REACT_APP_RECAPTCHA_SITE_KEY $RECAPTCHA_SITE_KEY

# install and cache app dependencies
ADD "https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h" skipcache
COPY package.json /usr/src/app
RUN npm install

# RUN npm install react-scripts@3.3.1 -g

# start app
CMD ["npm", "start"]
